import { NextRequest, NextResponse } from 'next/server';
import { spawn } from 'child_process';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import os from 'os';

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const file = formData.get('file') as File;
    const fileHash = formData.get('hash') as string;

    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    // 1. Temporarily store the file in the OS temp directory
    const buffer = Buffer.from(await file.arrayBuffer());
    const tempInputPath = join(os.tmpdir(), `mars_upload_${fileHash}.txt`);
    const tempOutputPath = join(os.tmpdir(), `mars_result_${fileHash}.json`);
    
    // In MVP, we write the raw buffer. In production, we'd extract text from PDF/Excel first.
    // Assuming the user is uploading the excel_summary.txt for now based on our python adapter.
    await writeFile(tempInputPath, buffer);

    console.log(`[API Bridge] File saved to ${tempInputPath}. Spawning Python engine...`);

    // 2. Spawn the Python Engine (Cross-Language Execution)
    // Use 'python3' as defined in our Hybrid Dockerfile
    const pythonScriptPath = join(process.cwd(), 'python_engine', 'scorecard_to_mars_adapter.py');
    
    return new Promise((resolve) => {
      const pyProcess = spawn('python3', [pythonScriptPath, tempInputPath, tempOutputPath]);

      pyProcess.stderr.on('data', (data) => {
        console.error(`[Python Engine Error]: ${data.toString()}`);
      });

      pyProcess.on('close', async (code) => {
        if (code !== 0) {
          resolve(NextResponse.json({ error: "Python engine failed during execution." }, { status: 500 }));
          return;
        }

        try {
          // 3. Read the JSON output generated by the Python engine
          const resultData = await readFile(tempOutputPath, 'utf-8');
          const jsonResult = JSON.parse(resultData);
          
          console.log(`[API Bridge] Successfully retrieved facts from Python engine.`);

          // Return the parsed Facts back to the React UI
          resolve(NextResponse.json({ 
            success: true, 
            hash: fileHash,
            facts: jsonResult 
          }));
        } catch (e) {
          resolve(NextResponse.json({ error: "Failed to parse Python engine output." }, { status: 500 }));
        }
      });
    });

  } catch (error: any) {
    console.error("[API Bridge] Server error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
